# vim: set foldmethod=marker:
[[plugins]]
repo = 'tpope/vim-dispatch'
[[plugins]]
repo = 'Shougo/vimproc.vim'# {{{
build = 'make'# }}}
[[plugins]]
repo = 'Shougo/unite.vim' #{{{
hook_add = '''
    let g:unite_force_overwrite_statusline = 0
    let g:unite_enable_start_insert = 0
    nnoremap <silent> <Leader>ub :<C-u>Unite buffer<CR>
    nnoremap <silent> <Leader>uf :<C-u>UniteWithBufferDir -buffer-name=files -start-insert file_rec/async<CR>
    nnoremap <silent> <Leader>ur :<C-u>Unite -buffer-name=register register<CR>
    nnoremap <silent> <Leader>um :<C-u>Unite file_mru<CR>
    nnoremap <silent> <Leader>uu :<C-u>Unite buffer file_mru<CR>
    " Unite All
    nnoremap <silent> <Leader>ua :<C-u>UniteWithBufferDir -buffer-name=files buffer file_mru bookmark file<CR>
    " UniteOutLine
    nnoremap <silent> <Leader>uo :<C-u>Unite -vertical -no-quit -winwidth=40 outline -direction=botright<CR>
    " „Ç¶„Ç£„É≥„Éâ„Ç¶„ÇíÂàÜÂâ≤„Åó„Å¶Èñã„Åè
    au FileType unite nnoremap <silent> <buffer> <expr> <C-j> unite#do_action('split')
    au FileType unite inoremap <silent> <buffer> <expr> <C-j> unite#do_action('split')
    " „Ç¶„Ç£„É≥„Éâ„Ç¶„ÇíÁ∏¶„Å´ÂàÜÂâ≤„Åó„Å¶Èñã„Åè
    au FileType unite nnoremap <silent> <buffer> <expr> <C-l> unite#do_action('vsplit')
    au FileType unite inoremap <silent> <buffer> <expr> <C-l> unite#do_action('vsplit')
    " „Çø„Éñ„ÅßÈñã„Åè
    au FileType unite nnoremap <silent> <buffer> <expr> <C-t> unite#do_action('tabopen')
    au FileType unite inoremap <silent> <buffer> <expr> <C-t> unite#do_action('tabopen')
    " ESC„Ç≠„Éº„Çí2ÂõûÊäº„Åô„Å®ÁµÇ‰∫Ü„Åô„Çã
    au FileType unite nmap <silent> <buffer> <ESC><ESC> q
    au FileType unite imap <silent> <buffer> <ESC><ESC> <ESC>q

    "nice unite and ag
    " let g:unite_source_history_yank_enable = 1
    " try
    let g:unite_source_rec_async_command =
                \ ['ag', '--follow', '--nocolor', '--nogroup',
                \  '--hidden', '-g', '']
    let g:unite_source_rec_max_cache_files = 5000
    call unite#filters#matcher_default#use(['matcher_fuzzy'])
    " catch
    " endtry
    " search a file in the filetree
    " nnoremap <space><space> :<C-u>Unite -start-insert file_rec/async<cr>
    " reset not it is <C-l> normally
    " nnoremap <space>r <Plug>(unite_restart)
'''# }}}
[[plugins]]
repo = 'Shougo/vimfiler.vim' #{{{
# on_cmd = ['VimFilerBufferDir', 'VimFilerCurrentDir']
depends = 'unite.vim'
hook_add = '''
    let g:vimfiler_force_overwrite_statusline = 0
    let g:vimfiler_enable_auto_cd = 1
    let g:vimfiler_as_default_explorer = 1
    nnoremap <silent> <Leader>e :VimFilerBufferDir -toggle -find -force-quit -split  -status -winwidth=35 -simple -split-action=below<CR>
    nnoremap <silent> <Leader>E :VimFilerCurrentDir -split -toggle -force-quit -status -winwidth=35 -simple -split-action=below<CR>
'''
# }}}
[[plugins]]
repo = 'Shougo/unite-outline'# {{{
depends = ['unite.vim']# }}}
[[plugins]]
repo = 'Shougo/neomru.vim'# {{{
depends = ['unite.vim']# }}}
[[plugins]]
repo = 'ujihisa/unite-colorscheme'# {{{
depends = ['unite.vim']# }}}
[[plugins]]
repo = 'Shougo/neossh.vim' # {{{
depends = ['unite.vim']# }}}
[[plugins]]
repo = 'Shougo/vimshell.vim'# {{{
depends = ['vimproc.vim']
hook_add = '''
let g:vimshell_prompt = "% "
let g:vimshell_secondary_prompt = "> "
let g:vimshell_user_prompt = 'getcwd()'
'''# }}}
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'# {{{
hook_add = '''
    " let g:ctrlp_cmd = "CtrlPMRUFiles"
    " yankround„ÅÆ„Å®„Åì„Çç„Åß„Éû„ÉÉ„Éî„É≥„Ç∞„ÅóÁõ¥„Åó„Å¶„ÅÑ„Çã
    let g:ctrlp_map = ''
    let g:ctrlp_extensions = ['mixed']
    let g:ctrlp_max_files = 5000
    nnoremap <space>m :<c-u>CtrlPMRUFiles<cr>
    nnoremap <space>c :<C-u>CtrlPCurWD<cr>
    nnoremap <space>r :<C-u>CtrlPClearCache<cr>
    nnoremap <space>b :<C-u>CtrlPBuffer<cr>
    nnoremap <space><space> :<C-u>CtrlP<cr>
    if executable('ag')
        if !has("win32")
            let g:ctrlp_use_caching=1
            let g:ctrlp_user_command='ag %s -i --follow --nocolor --nogroup -g ""'
        else
            let g:ctrlp_use_caching=1
            let g:ctrlp_user_command='ag -i --follow --nocolor --nogroup -g "" %s'
        endif
    endif
'''# }}}
[[plugins]]
repo = 'easymotion/vim-easymotion'# {{{
hook_add = '''
    let g:EasyMotion_do_mapping = 0
    nmap <Leader>s <Plug>(easymotion-overwin-f2)
'''# }}}
[[plugins]]
repo = 'kana/vim-submode'# {{{
hook_add = '''
    call submode#enter_with('winsize', 'n', '', '<C-w>>', '<C-w>>')
    call submode#enter_with('winsize', 'n', '', '<C-w><', '<C-w><')
    call submode#enter_with('winsize', 'n', '', '<C-w>+', '<C-w>+')
    call submode#enter_with('winsize', 'n', '', '<C-w>-', '<C-w>-')
    call submode#map('winsize', 'n', '', '>', '<C-w>>')
    call submode#map('winsize', 'n', '', '<', '<C-w><')
    call submode#map('winsize', 'n', '', '+', '<C-w>+')
    call submode#map('winsize', 'n', '', '-', '<C-w>-')
'''# }}}
[[plugins]]
repo = "tyru/restart.vim"
[[plugins]]
repo = 'superbrothers/vim-vimperator'
[[plugins]]
repo = "iamcco/markdown-preview.vim"# {{{
hook_add = '''
let g:mkdp_auto_close = 0
let g:mkdp_auto_open = 0
let g:mkdp_auto_start = 0
if has('win32') != 0
    let s:google_chrome_path="C:/Program\ Files/Google/Chrome/Application/chrome.exe"
    let s:google_chrome_path32="C:/Program\ Files\ (x86)/Google/Chrome/Application/chrome.exe"
    if executable(s:google_chrome_path)
        let g:mkdp_path_to_chrome=s:google_chrome_path
    else
        let g:mkdp_path_to_chrome=s:google_chrome_path32
    endif
endif
'''# }}}
[[plugins]]
repo = "nathanaelkane/vim-indent-guides"# {{{
hook_add = '''
    let g:indent_guides_guide_size = 0
    let g:indent_guides_color_change_percent = 5
    let g:indent_guides_start_level = 1
    let g:indent_guides_enable_on_vim_startup = 1
'''# }}}
# FOLD PLUGINS
[[plugins]]
repo = 'LeafCage/foldCC.vim'# {{{
hook_add = '''
    let g:foldCCtext_enable_autofdc_adjuster = 1
    let g:foldCCtext_head = ''
    " let g:foldCCtext_tail = '"(ÔæüÔΩ™Ôæü  )". (v:foldend-v:foldstart+1)'

    let g:foldCCtext_tail = 'printf(" %4d lines Lv%-2d", v:foldend-v:foldstart+1, v:foldlevel)'

    set foldtext=FoldCCtext()
    set fillchars=vert:\|
    " augroup FoldCC "{{{
    "     hi Folded gui=bold guibg=Grey28 guifg=gray80
    "     hi FoldColumn guibg=Grey14 guifg=gray80
    "
    "     " hi Folded gui=bold term=standout ctermbg=Grey ctermfg=DarkBlue guibg=Grey50 guifg=Grey80
    "     " hi FoldColumn gui=bold term=standout ctermbg=Grey ctermfg=DarkBlue guibg=Grey guifg=DarkBlue
    " augroup END "}}}
'''# }}}
[[plugins]]
repo = 'Konfekt/FastFold'
# STATUSLINE PLUGINS
[[plugins]]
repo = 'vim-airline/vim-airline'#{{{
hook_add = '''
    let g:airline#extensions#branch#enabled        = 1
    let g:airline#extensions#branch#empty_message  = ''
    " let g:airline#extensions#whitespace#checks     = [ 'indent',  'mixed-indent-file' ]
    let g:airline#extensions#syntastic#enabled     = 0

    let g:airline#extensions#tabline#enabled       = 1 "{{{
    " right side show mode
    let g:airline#extensions#tabline#show_tab_type = 1
    " „Éó„É¨„Éì„É•„Éº„Ç¶„Ç£„É≥„Éâ„Ç¶„ÅÆ„Çπ„ÉÜ„Éº„Çø„Çπ„É©„Ç§„É≥(AirlineÂÑ™ÂÖà:0„Åã,‰ªñ„ÅÆ„Éó„É©„Ç∞„Ç§„É≥ÂÑ™ÂÖà:1)
    let g:airline#extensions#tabline#exclude_preview = 0
    let g:airline#extensions#tabline#show_tabs = 1
    let g:airline#extensions#tabline#show_splits   = 1
    let g:airline#extensions#tabline#show_buffers = 0
    let g:airline#extensions#tabline#tab_nr_type   = 2 " splits and tab number
    let g:airline#extensions#tabline#show_close_button = 0 "}}}

    " let g:airline_powerline_fonts=1
    if !exists('g:airline_symbols')
        let g:airline_symbols = {}
    endif
    " powerline symbols" {{{
    if has("gui_running")
        let g:airline#extensions#tabline#left_sep      = '‚ÆÄ'
        let g:airline#extensions#tabline#left_alt_sep  = '‚ÆÅ'
        let g:airline#extensions#tabline#right_sep     = '‚ÆÇ'
        let g:airline#extensions#tabline#right_alt_sep = '‚ÆÉ'
        let g:airline_left_sep           = '‚ÆÄ'
        let g:airline_left_alt_sep       = '‚ÆÅ'
        let g:airline_right_sep          = '‚ÆÇ'
        let g:airline_right_alt_sep      = '‚ÆÉ'
        let g:airline_symbols.branch     = '‚≠†'
        let g:airline_symbols.readonly   = '‚≠§'
        let g:airline_symbols.linenr     = '‚≠°'
    else
        let g:airline_left_sep           = ''
        let g:airline_left_alt_sep       = ''
        let g:airline_right_sep          = ''
        let g:airline_right_alt_sep      = ''
    endif " }}}

    " unicode symobols# {{{
    " let g:airline_symbols.crypt = 'üîí'
    " let g:airline_symbols.linenr = '‚êä'
    " let g:airline_symbols.linenr = '‚ê§'
    " let g:airline_symbols.linenr = '¬∂'
    " let g:airline_symbols.maxlinenr = '‚ò∞'
    " let g:airline_symbols.maxlinenr = ''
    " let g:airline_symbols.branch = '‚éá'
    " let g:airline_symbols.paste = 'œÅ'
    " let g:airline_symbols.paste = '√û'
    " let g:airline_symbols.paste = '‚à•'
    " let g:airline_symbols.spell = 'Íû®'
    " let g:airline_symbols.notexists = '‚àÑ'
    " let g:airline_symbols.whitespace = 'Œû'# }}}

    " disable warning " {{{
    " let g:airline#extensions#default#layout = [
    "             \ [ 'a', 'b', 'c' ],
    "             \ [ 'x', 'y', 'z' ]
    "             \ ] " }}}
'''
# }}}
# PLUGINS FOR JAPANESE LANGUAGES
[[plugins]]
repo = "haya14busa/vim-migemo"
[[plugins]]
repo = "vim-jp/vimdoc-ja"

[[plugins]]
repo = 'tpope/vim-fugitive'
# [[plugins]]
# repo = "dbakker/vim-lint"
[[plugins]]
repo = 'tyru/open-browser.vim.git' # {{{
hook_add = '''
    let g:netrw_nogx = 1 " disable netrw's gx mapping.
    nmap gx <Plug>(openbrowser-smart-search)
    vmap gx <Plug>(openbrowser-smart-search)
'''# }}}
[[plugins]]
repo = "tmux-plugins/vim-tmux"
[[plugins]]
repo = "osyo-manga/vim-anzu"# {{{
hook_add = '''
" mapping
nmap n <Plug>(anzu-n-with-echo)
nmap N <Plug>(anzu-N-with-echo)
nmap * <Plug>(anzu-star-with-echo)
nmap # <Plug>(anzu-sharp-with-echo)

" clear status
" nmap <silent> <Esc><Esc> <Plug>(anzu-clear-search-status):noh<CR>


" statusline
set statusline=%{anzu#search_status()}


" if start anzu-mode key mapping
" anzu-mode is anzu(12/51) in screen
" nmap n <Plug>(anzu-mode-n)
" nmap N <Plug>(anzu-mode-N)
'''# }}}
[[plugins]]
repo = 'Valloric/YouCompleteMe'# {{{
# on_cmd = 'YcmCompleter'
hook_add = '''
    let g:ycm_global_ycm_extra_conf =
                \'~/.vim/dein/repos/github.com/Valloric/YouCompleteMe
                \/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'

    let g:ycm_min_num_of_chars_for_completion = 1
    let g:ycm_complete_in_comments = 1
    let g:ycm_collect_identifiers_from_comments_and_strings = 1
    let g:ycm_collect_identifiers_from_tags_files = 1
    let g:ycm_seed_identifiers_with_syntax = 1
    let g:ycm_add_preview_to_completeopt = 1
    let g:ycm_autoclose_preview_window_after_completion = 1
    " setting of the which python is used
    if has("unix")
        let g:ycm_python_binary_path = "/usr/bin/python" . g:myvimrc_python_version
        let g:UltiSnipsUsePythonVersion = g:myvimrc_python_version
    endif
    " let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
    " let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
    " let g:SuperTabDefaultCompletionType = '<C-n>'
'''# }}}
# [[plugins]]
# repo = 'ervandew/supertab'
[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
    " better key bindings for UltiSnipsExpandTrigger
    let g:UltiSnipsExpandTrigger = "<C-j>"
    let g:UltiSnipsJumpForwardTrigger = "<C-j>"
    let g:UltiSnipsJumpBackwardTrigger = "<C-k>"
    " let g:UltiSnipsSnippetsDir = "~/.vim/UltiSnips"
'''
[[plugins]]
repo = 'MarcWeber/vim-addon-mw-utils'
[[plugins]]
repo = 'tomtom/tlib_vim'
# [[plugins]]
# repo = 'garbas/vim-snipmate'
[[plugins]]
repo = 'honza/vim-snippets'
[[plugins]]
repo = "osyo-manga/shabadou.vim"
[[plugins]]
repo =  'othree/html5.vim'# {{{
on_ft = ['html']
hook_add = '''
    let g:html5_event_handler_attributes_complete = 1
    let g:html5_rdfa_attributes_complete = 1
    let g:html5_microdata_attributes_complete = 1
    let g:html5_aria_attributes_complete = 1
'''# }}}
[[plugins]]
repo = 'yomi322/neco-tweetvim.git'
[[plugins]]
repo =  'vim-scripts/JavaScript-Indent'# {{{
on_ft = 'javascript'# }}}
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'gregsexton/MatchTag'# {{{
on_ft = ['html','xml']# }}}
[[plugins]]
repo = 'basyura/twibill.vim.git'# {{{
depends = ['open-browser.vim']# }}}
[[plugins]]
repo = 'basyura/bitly.vim.git'
# COLORSCHEMES {{{
[[plugins]]
repo = 'joshdick/onedark.vim'
[[plugins]]
repo = 'sickill/vim-monokai'
[[plugins]]
repo = 'altercation/vim-colors-solarized'
[[plugins]]
repo = 'w0ng/vim-hybrid'
[[plugins]]
repo = 'vim-scripts/pyte'
[[plugins]]
repo = 'vim-scripts/summerfruit256.vim'
[[plugins]]
repo = 'ciaranm/inkpot'
[[plugins]]
repo = 'cdmedia/itg_flat_vim'
[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'rakr/vim-one'
# COLORSCHEMESE END }}}
# [[plugins]]
# repo = 'scrooloose/nerdtree' # {{{
#
# hook_add = '''
#     nnoremap <Leader>e :NERDTreeFind<CR>
#     nnoremap <Leader>E :NERDTreeCWD<CR>
#     augroup MyNERDTree
#         " NERDTree„ÅØË™≠„ÅøËæº„ÅøÊôÇ„Å´Ë®≠ÂÆöÊ∏à„Åø„Åã„Å©„ÅÜ„Åã„ÉÅ„Çß„ÉÉ„ÇØ„Åó„Å™„ÅÑÊ®°Êßò
#         autocmd VimEnter * let NERDTreeQuitOnOpen = 1
#         autocmd VimEnter * let NERDTreeMinimalUI = 1
#         autocmd VimEnter * let NERDTreeDirArrows = 1
#     augroup END
# '''
# # }}}
[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = '''
nmap p <Plug>(yankround-p)
xmap p <Plug>(yankround-p)
nmap P <Plug>(yankround-P)

nmap gp <Plug>(yankround-gp)
xmap gp <Plug>(yankround-gp)
nmap gP <Plug>(yankround-gP)

nnoremap <silent><SID>(ctrlp) :<C-u>CtrlP<CR>
nmap <expr><C-p> yankround#is_active() ? "\<Plug>(yankround-prev)" : "<SID>(ctrlp)"
nmap <C-n> <Plug>(yankround-next)
'''
# QUICKRUN SYNTAX CHECKS
[[plugins]]
repo = "thinca/vim-quickrun"
# {{{
# depends = "vim-watchdogs"
# on_event = "VimEnter"
# on_cmd = 'QuickRun'
hook_add = '''

    let g:quickrun_config = get(g:, 'quickrun_config', {})

    let g:quickrun_config._ = {
                    \ 'runner'    : 'vimproc',
                    \ "runner/vimproc/updatetime" : 100,
                    \ "outputter/quickfix/open_cmd" : "copen 8"
                    \}
                " \ 'runner'    : 'job',
                " \ 'runner/job/interval' : 100,
                " \ 'outputter/buffer/into': 1,
                " \ 'outputter/buffer/close_on_empty' : 0,
                " \ }
    " \ 'runner'    : 'vimproc',
    " \ 'runner/vimproc/updatetime' : 100,
    let g:quickrun_config.python = {
                \ 'command' : 'python',
                \ 'cmdopt' : '-u'
                \ }
    let g:quickrun_config.markdown = {
                \ 'type': 'markdown/pandoc',
                \ 'cmdopt': '-s',
                \ 'outputter': 'browser'
                \ }

    " nnoremap <silent> <Leader>R :QuickRun<CR>
    " nmap <Leader>R <Plug>(quickrun)
    nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"

'''
# }}}
[[plugins]]
repo = "osyo-manga/vim-watchdogs"
# on_cmd = 'WatchdogsRun'
depends = [ 'shabadou.vim', 'vim-quickrun' ]
# {{{

hook_add = '''

    let g:watchdogs_check_BufWritePost_enable = 1
    let g:watchdogs_check_BufWritePost_enables = {
                \"cpp" : 0
                \}
    let g:watchdogs_check_CursorHold_enable = 0

    " quickrun-hook-add-include-option {{{
    let s:hook = {
                \ "name": "add_include_option",
                \ "kind": "hook",
                \ "config": {
                \   "enable": 0,
                \   },
                \ }

    function! s:hook.on_module_loaded(session, context)
        let paths = filter(split(&path, ","), "len(v:val) && v:val !='.' && v:val !~ 'mingw'")
        if len(paths)
            let a:session.config.cmdopt .= " -I".join(paths, " -I")
        endif
    endfunction
    call quickrun#module#register(s:hook, 1)
    unlet s:hook
    " }}}

    let s:config = {
                \"cpp" : {
                \    "hook/add_include_option/enable" : 1
                \    },
                \"cpp/watchdogs_checker" : {
                \    "type" : "watchdogs_checker/clang++",
                \    "hook/add_include_option/enable" : 1,
                \    "cmdopt" : '-std=c++11 -Wall'
                \   },
                \}
                " \ "vim/watchdogs_checker" : {
                " \   "type" : "watchdogs_checker/vint",
                " \   },
    call extend(g:quickrun_config, s:config)
    unlet s:config

    " if has("job")
    "     let g:quickrun_config["watchdogs_checker/_"] = {
    "                 \ 'runner'    : 'job',
    "                 \ 'runner/job/interval' : 100,
    "                 \ "outputter/quickfix/open_cmd" : "copen 8"
    "                 \}
    " else
        let g:quickrun_config["watchdogs_checker/_"] = {
                    \ 'runner'    : 'vimproc',
                    \ "runner/vimproc/updatetime" : 100,
                    \ "outputter/quickfix/open_cmd" : "copen 5"
                    \}
                    "
     " endif
     call watchdogs#setup(g:quickrun_config)
'''
# }}}

# [[plugins]]
# repo = 'mileszs/ack.vim'
# hook_add = '''
#     let g:ackprg = 'ag --vimgrep --smart-case'
# '''
