# vim: set foldmethod=marker:
[[plugins]]
repo = 'tpope/vim-dispatch'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
[[plugins]]
repo = 'Shougo/vimfiler.vim'
# on_cmd = ['VimFilerBufferDir', 'VimFilerCurrentDir']
depends = 'unite.vim'
[[plugins]]
repo = 'Shougo/unite-outline'
depends = ['unite.vim']
[[plugins]]
repo = 'Shougo/neomru.vim'
depends = ['unite.vim']
[[plugins]]
repo = 'ujihisa/unite-colorscheme'
depends = ['unite.vim']
[[plugins]]
repo = 'Shougo/neossh.vim'
depends = ['unite.vim']
[[plugins]]
repo = 'Shougo/vimshell.vim'
depends = ['vimproc.vim']
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
[[plugins]]
repo = 'mattn/ctrlp-filer'
depends = 'ctrlp.vim'
[[plugins]]
repo = 'easymotion/vim-easymotion'
[[plugins]]
repo = 'superbrothers/vim-vimperator'
[[plugins]]
repo = "nathanaelkane/vim-indent-guides"
[[plugins]]
repo = 'LeafCage/foldCC.vim'
[[plugins]]
repo = 'Konfekt/FastFold'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
[[plugins]]
repo = "haya14busa/vim-migemo"
[[plugins]]
repo = "vim-jp/vimdoc-ja"
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'tyru/open-browser.vim.git'
[[plugins]]
repo = "tmux-plugins/vim-tmux"
[[plugins]]
repo = "osyo-manga/vim-anzu"
[[plugins]]
repo = 'SirVer/ultisnips'
merged = 0
[[plugins]]
repo = 'ervandew/supertab'
[[plugins]]
repo = 'MarcWeber/vim-addon-mw-utils'
[[plugins]]
repo = 'tomtom/tlib_vim'
[[plugins]]
repo = 'honza/vim-snippets'
[[plugins]]
repo = "osyo-manga/shabadou.vim"
[[plugins]]
repo =  'othree/html5.vim'
on_ft = ['html']
[[plugins]]
repo = 'yomi322/neco-tweetvim.git'
[[plugins]]
repo =  'vim-scripts/JavaScript-Indent'
on_ft = 'javascript'
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'gregsexton/MatchTag'
on_ft = ['html','xml']
[[plugins]]
repo = 'basyura/twibill.vim.git'
depends = ['open-browser.vim']
[[plugins]]
repo = 'basyura/bitly.vim.git'
[[plugins]]
repo = 'LeafCage/yankround.vim'
[[plugins]]
repo = 'tyru/caw.vim.git'
# on_event = "CursorMoved"
[[plugins]]
repo = 'tpope/vim-surround'
# on_event = "CursorMoved"
[[plugins]]
repo = 'junegunn/vim-easy-align'
# on_event = "CursorMoved"
[[plugins]]
repo = 'istepura/vim-toolbar-icons-silk'
[[plugins]]
repo = "justinmk/vim-dirvish"
# on_event = 'VimEnter'
# on_cmd = "Dirvish"
[[plugins]]
repo = 'terryma/vim-multiple-cursors'
[[plugins]]
repo = "mbbill/undotree"
# on_event = "VimEnter"
# on_if = '!has("python")'
[[plugins]]
repo = "haya14busa/dein-command.vim"

[[plugins]]
repo = 'joshdick/onedark.vim'
[[plugins]]
repo = 'sickill/vim-monokai'
[[plugins]]
repo = 'altercation/vim-colors-solarized'
[[plugins]]
repo = 'w0ng/vim-hybrid'
[[plugins]]
repo = 'vim-scripts/pyte'
[[plugins]]
repo = 'vim-scripts/summerfruit256.vim'
[[plugins]]
repo = 'ciaranm/inkpot'
[[plugins]]
repo = 'cdmedia/itg_flat_vim'
[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'rakr/vim-one'
