# vim: set foldmethod=marker:
[[plugins]]
repo = 'tpope/vim-dispatch'
[[plugins]]
repo = 'Shougo/vimproc.vim' # {{{
build = 'make' # }}}
[[plugins]]
repo = 'Shougo/vimfiler.vim' # {{{
# on_cmd = ['VimFilerBufferDir', 'VimFilerCurrentDir']
depends = 'unite.vim'
hook_add = '''
	let g:vimfiler_force_overwrite_statusline = 0
	let g:vimfiler_enable_auto_cd = 1
	let g:vimfiler_as_default_explorer = 0
	nnoremap <silent> <Leader>e :VimFilerBufferDir -split -winwidth=35 -simple -toggle -find -force-quit -status -split-action=below<CR>
	nnoremap <silent> <Leader>E :VimFilerCurrentDir -split -winwidth=35 -simple -toggle -force-quit -status -split-action=below<CR>
	" nnoremap <silent> <Leader>e :VimFilerBufferDir -toggle -find -force-quit -split  -status -winwidth=35 -simple -split-action=below<CR>
	" nnoremap <silent> <Leader>E :VimFilerCurrentDir -split -toggle -force-quit -status -winwidth=35 -simple -split-action=below<CR>
'''
# }}}
[[plugins]]
repo = 'Shougo/unite-outline' # {{{
depends = ['unite.vim'] # }}}
[[plugins]]
repo = 'Shougo/neomru.vim' # {{{
depends = ['unite.vim'] # }}}
[[plugins]]
repo = 'ujihisa/unite-colorscheme' # {{{
depends = ['unite.vim'] # }}}
[[plugins]]
repo = 'Shougo/neossh.vim' # {{{
depends = ['unite.vim'] # }}}
[[plugins]]
repo = 'Shougo/vimshell.vim' # {{{
depends = ['vimproc.vim']
hook_add = '''
let g:vimshell_prompt = "% "
let g:vimshell_secondary_prompt = "> "
let g:vimshell_user_prompt = 'getcwd()'
''' # }}}
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim' # {{{
hook_add = '''
	" let g:ctrlp_cmd = "CtrlPMRUFiles"
	" yankroundã®ã¨ã“ã‚ã§ãƒãƒƒãƒ”ãƒ³ã‚°ã—ç›´ã—ã¦ã„ã‚‹
	let g:ctrlp_map = ''
	" let g:ctrlp_extensions = ['mixed']
	let g:ctrlp_max_files = 5000
	let g:ctrlp_match_window = "max:30"
	nnoremap <Leader>mr :<c-u>CtrlPMRUFiles<cr>
	nnoremap <Leader>c :<C-u>CtrlPCurWD<cr>
	" nnoremap <Leader>r :<C-u>CtrlPClearCache<cr>
	nnoremap <Leader>b :<C-u>CtrlPBuffer<cr>
	nnoremap <Leader><Leader> :<C-u>CtrlP<cr>
	if executable('ag')
		if !has("win32")
			let g:ctrlp_use_caching=1
			let g:ctrlp_user_command='ag %s -i --follow --nocolor --nogroup -g ""'
		else
			let g:ctrlp_use_caching=1
			let g:ctrlp_user_command='ag -i --follow --nocolor --nogroup -g "" %s'
		endif
	endif
''' # }}}
[[plugins]]
repo = 'mattn/ctrlp-filer' # {{{
depends = 'ctrlp.vim'
hook_add = '''
	nnoremap <Leader>f :<C-u>CtrlPFiler<cr>
''' # }}}
[[plugins]]
repo = 'easymotion/vim-easymotion' # {{{
hook_add = '''
	let g:EasyMotion_do_mapping = 0
	nmap <Leader>s <Plug>(easymotion-overwin-f2)
''' # }}}
[[plugins]]
repo = 'superbrothers/vim-vimperator'
[[plugins]]
repo = "nathanaelkane/vim-indent-guides" # {{{
hook_add = '''
	let g:indent_guides_guide_size = 0
	let g:indent_guides_color_change_percent = 5
	let g:indent_guides_start_level = 1
	let g:indent_guides_enable_on_vim_startup = 1
''' # }}}
[[plugins]]
repo = 'LeafCage/foldCC.vim' # {{{
hook_add = '''
	let g:foldCCtext_enable_autofdc_adjuster = 1
	let g:foldCCtext_head = ''
	" let g:foldCCtext_tail = '"(ï¾Ÿï½ªï¾Ÿ  )". (v:foldend-v:foldstart+1)'

	let g:foldCCtext_tail = 'printf(" %4d lines Lv%-2d", v:foldend-v:foldstart+1, v:foldlevel)'

	set foldtext=FoldCCtext()
	set fillchars=vert:\|
	" augroup FoldCC "{{{
	"	 hi Folded gui=bold guibg=Grey28 guifg=gray80
	"	 hi FoldColumn guibg=Grey14 guifg=gray80
	"
	"	 " hi Folded gui=bold term=standout ctermbg=Grey ctermfg=DarkBlue guibg=Grey50 guifg=Grey80
	"	 " hi FoldColumn gui=bold term=standout ctermbg=Grey ctermfg=DarkBlue guibg=Grey guifg=DarkBlue
	" augroup END "}}}
''' # }}}
[[plugins]]
repo = 'Konfekt/FastFold'
[[plugins]]
repo = 'vim-airline/vim-airline' # {{{
hook_add = '''
	let g:airline#extensions#branch#enabled		= 1
	let g:airline#extensions#branch#empty_message  = ''
	" let g:airline#extensions#whitespace#checks	 = [ 'indent',  'mixed-indent-file' ]
	let g:airline#extensions#syntastic#enabled	 = 0

	let g:airline#extensions#tabline#enabled	   = 1 "{{{
	" right side show mode
	let g:airline#extensions#tabline#show_tab_type = 1
	" ãƒ—ãƒ¬ãƒ“ãƒ¥ãƒ¼ã‚¦ã‚£ãƒ³ãƒ‰ã‚¦ã®ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ãƒ©ã‚¤ãƒ³(Airlineå„ªå…ˆ:0ã‹,ä»–ã®ãƒ—ãƒ©ã‚°ã‚¤ãƒ³å„ªå…ˆ:1)
	let g:airline#extensions#tabline#exclude_preview = 0
	let g:airline#extensions#tabline#show_tabs = 1
	let g:airline#extensions#tabline#show_splits   = 1
	let g:airline#extensions#tabline#show_buffers = 0
	let g:airline#extensions#tabline#tab_nr_type   = 2 " splits and tab number
	let g:airline#extensions#tabline#show_close_button = 0 "}}}

	" let g:airline_powerline_fonts=1
	if !exists('g:airline_symbols')
		let g:airline_symbols = {}
	endif
	" powerline symbols" {{{
	if has("gui_running")
		let g:airline#extensions#tabline#left_sep	  = 'â®€'
		let g:airline#extensions#tabline#left_alt_sep  = 'â®'
		let g:airline#extensions#tabline#right_sep	 = 'â®‚'
		let g:airline#extensions#tabline#right_alt_sep = 'â®ƒ'
		let g:airline_left_sep		   = 'â®€'
		let g:airline_left_alt_sep	   = 'â®'
		let g:airline_right_sep		  = 'â®‚'
		let g:airline_right_alt_sep	  = 'â®ƒ'
		let g:airline_symbols.branch	 = 'â­ '
		let g:airline_symbols.readonly   = 'â­¤'
		let g:airline_symbols.linenr	 = 'â­¡'
	else
		let g:airline_left_sep		   = ''
		let g:airline_left_alt_sep	   = ''
		let g:airline_right_sep		  = ''
		let g:airline_right_alt_sep	  = ''
	endif " }}}

	" unicode symobols# {{{
	" let g:airline_symbols.crypt = 'ğŸ”’'
	" let g:airline_symbols.linenr = 'âŠ'
	" let g:airline_symbols.linenr = 'â¤'
	" let g:airline_symbols.linenr = 'Â¶'
	" let g:airline_symbols.maxlinenr = 'â˜°'
	" let g:airline_symbols.maxlinenr = ''
	" let g:airline_symbols.branch = 'â‡'
	" let g:airline_symbols.paste = 'Ï'
	" let g:airline_symbols.paste = 'Ã'
	" let g:airline_symbols.paste = 'âˆ¥'
	" let g:airline_symbols.spell = 'ê¨'
	" let g:airline_symbols.notexists = 'âˆ„'
	" let g:airline_symbols.whitespace = 'Î'# }}}

	" disable warning " {{{
	" let g:airline#extensions#default#layout = [
	"			 \ [ 'a', 'b', 'c' ],
	"			 \ [ 'x', 'y', 'z' ]
	"			 \ ] " }}}
''' # }}}
[[plugins]]
repo = 'vim-airline/vim-airline-themes' # {{{
depends = 'vim-airline'
# }}}
[[plugins]]
repo = "haya14busa/vim-migemo"
[[plugins]]
repo = "vim-jp/vimdoc-ja"
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'tyru/open-browser.vim.git' # {{{
hook_add = '''
	let g:netrw_nogx = 1 " disable netrw's gx mapping.
	nmap gx <Plug>(openbrowser-smart-search)
	vmap gx <Plug>(openbrowser-smart-search)
''' # }}}
[[plugins]]
repo = "tmux-plugins/vim-tmux"
[[plugins]]
repo = "osyo-manga/vim-anzu" # {{{
hook_add = '''
" mapping
nmap n <Plug>(anzu-n-with-echo)
nmap N <Plug>(anzu-N-with-echo)
nmap * <Plug>(anzu-star-with-echo)
nmap # <Plug>(anzu-sharp-with-echo)

" if start anzu-mode key mapping
" anzu-mode is anzu(12/51) in screen
" nmap n <Plug>(anzu-mode-n)
" nmap N <Plug>(anzu-mode-N)
''' # }}}
[[plugins]]
repo = 'SirVer/ultisnips' # {{{
merged = 0
hook_add = '''
	" better key bindings for UltiSnipsExpandTrigger
	let g:UltiSnipsExpandTrigger = "<c-j>"
	let g:UltiSnipsJumpForwardTrigger = "<c-j>"
	let g:UltiSnipsJumpBackwardTrigger = "<c-k>"
	" let g:UltiSnipsSnippetsDir = "~/.vim/UltiSnips"
	if has("unix")
		if !g:myvimrc_python_version == ""
			let g:UltiSnipsUsePythonVersion = g:myvimrc_python_version
		else
			let g:UltiSnipsUsePythonVersion = 2
		endif
	endif
''' # }}}
[[plugins]]
repo = 'ervandew/supertab'# {{{
hook_add = '''
	let g:SuperTabDefaultCompletionType = '<c-n>'
'''# }}}
[[plugins]]
repo = 'MarcWeber/vim-addon-mw-utils'
[[plugins]]
repo = 'tomtom/tlib_vim'
[[plugins]]
repo = 'honza/vim-snippets'
[[plugins]]
repo = "osyo-manga/shabadou.vim"
[[plugins]]
repo =  'othree/html5.vim' # {{{
on_ft = ['html']
hook_add = '''
	let g:html5_event_handler_attributes_complete = 1
	let g:html5_rdfa_attributes_complete = 1
	let g:html5_microdata_attributes_complete = 1
	let g:html5_aria_attributes_complete = 1
''' # }}}
[[plugins]]
repo = 'yomi322/neco-tweetvim.git'
[[plugins]]
repo =  'vim-scripts/JavaScript-Indent' # {{{
on_ft = 'javascript' # }}}
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'gregsexton/MatchTag' # {{{
on_ft = ['html','xml'] # }}}
[[plugins]]
repo = 'basyura/twibill.vim.git' # {{{
depends = ['open-browser.vim'] # }}}
[[plugins]]
repo = 'basyura/bitly.vim.git'
[[plugins]]
repo = 'LeafCage/yankround.vim' # {{{
hook_add = '''
	nmap p <Plug>(yankround-p)
	xmap p <Plug>(yankround-p)
	nmap P <Plug>(yankround-P)

	nmap gp <Plug>(yankround-gp)
	xmap gp <Plug>(yankround-gp)
	nmap gP <Plug>(yankround-gP)

	nnoremap <silent><SID>(ctrlp) :<C-u>CtrlP<CR>
	nmap <expr><C-p> yankround#is_active() ? "\<Plug>(yankround-prev)" : "<SID>(ctrlp)"
	nmap <C-n> <Plug>(yankround-next)
''' # }}}
[[plugins]]
repo = 'tyru/caw.vim.git' # {{{
# on_event = "CursorMoved" # }}}
[[plugins]]
repo = 'tpope/vim-surround' # {{{
# on_event = "CursorMoved" # }}}
[[plugins]]
repo = 'junegunn/vim-easy-align' # {{{
# on_event = "CursorMoved"
hook_add = '''
	" ãƒ´ã‚£ã‚¸ãƒ¥ã‚¢ãƒ«ãƒ¢ãƒ¼ãƒ‰ã§é¸æŠã—ï¼Œeasy-align å‘¼ã‚“ã§æ•´å½¢ï¼(e.g. vip<Enter>)
	vmap <Enter> <Plug>(LiveEasyAlign)

	" easy-align ã‚’å‘¼ã‚“ã ä¸Šã§ï¼Œç§»å‹•ã—ãŸã‚Šãƒ†ã‚­ã‚¹ãƒˆã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã‚’æŒ‡å®šã—ã¦æ•´å½¢ï¼(e.g. gaip)
	" nmap ga <Plug>(EasyAlign)
	" " Start interactive EasyAlign in visual mode (e.g. vipga)
	" xmap ga <Plug>(EasyAlign)
''' # }}}
[[plugins]]
repo = 'istepura/vim-toolbar-icons-silk'
[[plugins]]
repo = "justinmk/vim-dirvish"# {{{
# on_event = 'VimEnter'
# on_cmd = "Dirvish"
hook_add = '''

nnoremap <silent> <Leader>d :let w:dirvishbefore=expand("%:p")<cr>:Dirvish %:p:h<cr>
nnoremap <silent> <Leader>D :Dirvish<cr>

fun s:mydirvish_selectbeforedir()
	if exists("w:dirvishbefore") 
		call search('\V\^'.escape(w:dirvishbefore, '\').'\$', 'cw')
	endif
endf

augroup mydirvish
	autocmd!
	" hã¨lã«ã‚ˆã‚‹ç§»å‹•
	autocmd FileType dirvish nnoremap <silent><buffer> l :call dirvish#open('edit', 0)<CR>
	autocmd FileType dirvish xnoremap <silent><buffer> l :call dirvish#open('edit', 0)<CR>
	autocmd FileType dirvish nmap <silent><buffer> h <Plug>(dirvish_up)
	autocmd FileType dirvish xmap <silent><buffer> h <Plug>(dirvish_up)
	" èµ·å‹•æ™‚ã«ã‚½ãƒ¼ãƒˆ è¡Œæœ«è¨˜å·ã‚’å…¥ã‚Œãªã„ã“ã¨ã§å…¨éƒ¨ã‚½ãƒ¼ãƒˆã™ã‚‹
	autocmd FileType dirvish silent sort /.*\([\\\/]\)\@=/
	" autocmd FileType dirvish silent keeppatterns g@\v[\/]\.[^\/]+[\/]?$@d
	" .ã¨sã«éš ã—ãƒ•ã‚¡ã‚¤ãƒ«ã¨ã‚½ãƒ¼ãƒˆã‚’å‰²ã‚Šå½“ã¦
	autocmd FileType dirvish nnoremap <silent><buffer> . :keeppatterns g@\v[\/]\.[^\/]+[\/]?$@d<cr>
	" è¡Œæœ«è¨˜å·ã‚’å…¥ã‚Œãªã„ã“ã¨ã§å…¨éƒ¨ã‚½ãƒ¼ãƒˆã™ã‚‹
	autocmd FileType dirvish nnoremap <silent><buffer> s :sort /.*\([\\\/]\)\@=/<cr>

	" é–‹ã„ã¦ã„ãŸãƒ•ã‚¡ã‚¤ãƒ«ã‚„Directory(w:dirvishbefore)ã«ã‚«ãƒ¼ã‚½ãƒ«ã‚’ã‚ã‚ã›ã‚‹
	autocmd FileType dirvish call <SID>mydirvish_selectbeforedir()
	autocmd FileType dirvish let w:dirvishbefore=expand("%:p")
augroup END
'''
# }}}
[[plugins]]
repo = 'terryma/vim-multiple-cursors' # {{{
hook_add = '''
let g:multi_cursor_use_default_mapping = 0
" Default mapping
let g:multi_cursor_start_key = 'g<C-n>'
let g:multi_cursor_next_key = '<C-n>'
let g:multi_cursor_prev_key = '<C-p>'
let g:multi_cursor_skip_key = '<C-x>'
let g:multi_cursor_quit_key = '<Esc>'
''' # }}}
[[plugins]]
repo = "mbbill/undotree" # {{{
# on_event = "VimEnter"
# on_if = '!has("python")'
hook_add = '''
	let g:undotree_WindowLayout = 2
	let g:undotree_SplitWidth = 30
	nnoremap <Leader>gu :<C-u>UndotreeToggle<cr>
''' # }}}
[[plugins]]
repo = "haya14busa/dein-command.vim"

# COLORSCHEMES {{{
[[plugins]]
repo = 'joshdick/onedark.vim'
[[plugins]]
repo = 'sickill/vim-monokai'
[[plugins]]
repo = 'altercation/vim-colors-solarized'
[[plugins]]
repo = 'w0ng/vim-hybrid'
[[plugins]]
repo = 'vim-scripts/pyte'
[[plugins]]
repo = 'vim-scripts/summerfruit256.vim'
[[plugins]]
repo = 'ciaranm/inkpot'
[[plugins]]
repo = 'cdmedia/itg_flat_vim'
[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'rakr/vim-one'
# COLORSCHEMESE END }}}
